spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/correspondencia
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nicolasmoyanosoftware@gmail.com
    password: mgdhtzkoythsmhtk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

server:
  port: 8081

app:
  jwt:
    secret: "cambiarPorUnaClaveMuyLargaYSecretaDeAlMenos256BitsEnProduccionPorFavor1234567890"
    expiration-ms: 900000             # 15 minutos (access token corto)
    refresh-expiration-ms: 604800000  # 7 días (refresh token largo)
  uploads:
    dir: ./uploads
  cors:
    allowed-origins: http://localhost:5173
  frontend-url: http://localhost:5173
  sistema-nombre: "Sistema de Correspondencia y PQRS"